#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Path
export PATH="$PATH:$HOME/.bin"
export PATH="$PATH:$HOME/go/bin"

# Shortcut
alias c='clear'
alias o='open'
alias xcpath='$HOME/Library/Developer/Xcode/'

# Proxy
# Surge
alias setproxy='export ALL_PROXY=http://127.0.0.1:6152'
alias unsetproxy='unset ALL_PROXY'
alias lookupip='curl -i http://ip.cn'

# SIP 
alias sipenable='sudo spctl --master-enable'
alias sipdisable='sudo spctl --master-disable'

# aria2c
alias aria2_rpc='/usr/local/bin/aria2c --enable-rpc=true --input-file=/Users/edison/.aria2/aria2.session --conf-path=/Users/edison/.aria2/aria2.conf'

# DNS
alias flushdns='sudo killall -HUP mDNSResponder'

# gitignore.io
function gi() { curl -L -s https://www.gitignore.io/api/$@ ;}
alias giios='touch .gitignore && gi macos,xcode,appcode,cocoapods,carthage,swift,objective-c >> .gitignore'

# git
alias gcl='git clone --recursive'
alias gst='git status'

# Utils
# battery
function battery() {
    ioreg  -r -k "BatteryPercent" | awk -F " = " '/"Product" = / {print $2":"} /"BatteryPercent" = / {print $2"%"}' |  sed 'N;s/\n/ /;' | sed -e 's/"//g'
}

# files
# remove files recursively
function rmfr() {
	find $1 -type f -name $2 -delete
}

# hh
export HISTFILE=~/.zsh_history  # ensure history file visibility
export HH_CONFIG=hicolor        # get more colors
bindkey -s "\C-r" "\eqhh\n"     # bind hh to Ctrl-r (for Vi mode check doc)

# theos
export THEOS=/opt/theos
export PATH=/opt/theos/bin/:$PATH

# MonkeyDev
export MonkeyDevPath=/opt/MonkeyDev
export MonkeyDevDeviceIP=
export PATH=/opt/MonkeyDev/bin:$PATH

# rust
export PATH="$HOME/.cargo/bin:$PATH"
