#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Path
export PATH="$PATH:$HOME/.bin"
export PATH="$PATH:$HOME/go/bin"

# Shortcut
alias c='clear'
alias o='open'
alias xcpath='$HOME/Library/Developer/Xcode/'

# Proxy
# Surge
alias setproxy='export ALL_PROXY=http://127.0.0.1:6152'
alias unsetproxy='unset ALL_PROXY'
alias lookupip='curl -i http://ip.cn'

# SIP 
alias sipenable='sudo spctl --master-enable'
alias sipdisable='sudo spctl --master-disable'

# aria2c
alias aria='aria2c -c -s10 -x10 -k1M'

# DNS
alias flushdns='sudo killall -HUP mDNSResponder'

# gitignore.io
function gi() { curl -L -s https://www.gitignore.io/api/$@ ;}
alias giios='touch .gitignore && gi macos,xcode,appcode,cocoapods,carthage,swift,objective-c >> .gitignore'

# git
alias gcl='git clone --recursive'
alias gst='git status'

# Utils
# battery
function battery() {
    ioreg  -r -k "BatteryPercent" | awk -F " = " '/"Product" = / {print $2":"} /"BatteryPercent" = / {print $2"%"}' |  sed 'N;s/\n/ /;' | sed -e 's/"//g'
}
